/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clase.imagen1;
import clase.imagen2;
import clase.imagen3;
import javax.swing.JOptionPane;

public class frmCasino extends javax.swing.JFrame {

    int aleatorio1, aleatorio2, aleatorio3, valorf = 100;
    static int valorI;
    imagen1 img1 = new imagen1();
    imagen2 img2 = new imagen2();
    imagen3 img3 = new imagen3();

    public frmCasino() {
        initComponents();
        setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(lblFondo, "src/imagenes/casino.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblMaquina, "src/imagenes/maquina.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblF1, "src/imagenes/esmeralda.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblF2, "src/imagenes/moneda.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblF3, "src/imagenes/fresa.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblF4, "src/imagenes/calavera.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(btnEmpezar, "src/imagenes/start.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(btnPausar, "src/imagenes/stop.png");
        valorI = frmInicio.inicial;
        lblPuntaje.setText(String.valueOf(valorI));
        img1.setImagen1(lbl1);
        img2.setImagen2(lbl3);
        img3.setImagen3(lbl2);
        img1.start();
        img2.start();
        img3.start();
        img1.suspend();
        img2.suspend();
        img3.suspend();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        lblMaquina = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblF1 = new javax.swing.JLabel();
        lblF3 = new javax.swing.JLabel();
        lblF2 = new javax.swing.JLabel();
        lblF4 = new javax.swing.JLabel();
        lblV1 = new javax.swing.JLabel();
        lblV2 = new javax.swing.JLabel();
        lblV3 = new javax.swing.JLabel();
        lblV4 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JLabel();
        btnPausar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblPuntaje = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 70, 70));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 70, 70));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 70, 70));
        jPanel1.add(lblMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 380, 230));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Casino ITSCO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 210, 50));
        jPanel1.add(lblF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 30, 30));
        jPanel1.add(lblF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 30, 30));
        jPanel1.add(lblF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 30, 30));
        jPanel1.add(lblF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 30, 30));

        lblV1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblV1.setForeground(new java.awt.Color(204, 204, 0));
        lblV1.setText("$20");
        jPanel1.add(lblV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, 30));

        lblV2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblV2.setForeground(new java.awt.Color(204, 204, 0));
        lblV2.setText("$10");
        jPanel1.add(lblV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, 30));

        lblV3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblV3.setForeground(new java.awt.Color(204, 204, 0));
        lblV3.setText("$5");
        jPanel1.add(lblV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, 30));

        lblV4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblV4.setForeground(new java.awt.Color(204, 204, 0));
        lblV4.setText("$-5");
        jPanel1.add(lblV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, 30));

        btnEmpezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpezarMouseClicked(evt);
            }
        });
        jPanel1.add(btnEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 70, 70));

        btnPausar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPausarMouseClicked(evt);
            }
        });
        jPanel1.add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 60, 60));

        jPanel5.setBackground(new java.awt.Color(102, 102, 0));

        lblPuntaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPuntaje.setForeground(new java.awt.Color(0, 153, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puntaje:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 80, -1));

        lblFondo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 630, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpezarMouseClicked
        img1.resume();
        img2.resume();
        img3.resume();


    }//GEN-LAST:event_btnEmpezarMouseClicked

    private void btnPausarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPausarMouseClicked
        img1.suspend();
        img2.suspend();
        img3.suspend();

        aleatorio1 = img1.getAleatorio();
        aleatorio2 = img2.getAleatorio();
        aleatorio3 = img3.getAleatorio();
        //INSTANCIANDO HILOS
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                valorf = 5;
                valorf = valorI + valorf;
                try {
                    while (valorI <= valorf) {
                        lblPuntaje.setText(String.valueOf(valorI));
                        Thread.sleep(100);
                        valorI++;
                    }
                } catch (Exception e) {
                }
            }
        });
        Thread t2 = new Thread(new Runnable() {
            @Override
            public void run() {
                valorf = 10;
                valorf = valorI + valorf;
                try {
                    while (valorI <= valorf) {
                        lblPuntaje.setText(String.valueOf(valorI));
                        Thread.sleep(100);
                        valorI++;
                    }
                } catch (Exception e) {
                }
            }
        });
        Thread t3 = new Thread(new Runnable() {
            @Override
            public void run() {
                valorf = 20;
                valorf = valorI + valorf;
                try {
                    while (valorI <= valorf) {
                        lblPuntaje.setText(String.valueOf(valorI));
                        Thread.sleep(100);
                        valorI++;
                    }
                } catch (Exception e) {
                }
            }
        });
        Thread t4 = new Thread(new Runnable() {
            @Override
            public void run() {
                valorf = -5;
                valorf = valorf + valorI;
                try {
                    while (valorI >= valorf) {
                        lblPuntaje.setText(String.valueOf(valorI));
                        Thread.sleep(100);
                        valorI--;
                    }
                } catch (Exception e) {
                }
            }
        });
        if (aleatorio1 == 0 && aleatorio2 == 0 && aleatorio3 == 0) {
            t1.start();
            JOptionPane.showMessageDialog(null, "Ganaste");
        } else if (aleatorio1 == 1 && aleatorio2 == 1 && aleatorio3 == 1) {
            t2.start();
            JOptionPane.showMessageDialog(null, "Ganaste");
        } else if (aleatorio1 == 2 && aleatorio2 == 2 && aleatorio3 == 2) {
            t3.start();
            JOptionPane.showMessageDialog(null, "Ganaste");
        } else if (aleatorio1 == 3 && aleatorio2 == 3 && aleatorio3 == 3) {
            t4.start();
            JOptionPane.showMessageDialog(null, "Perdiste");
        }

        t1.suspend();
        t2.suspend();
        t3.suspend();
        t4.suspend();
    }//GEN-LAST:event_btnPausarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCasino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCasino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCasino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCasino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCasino().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEmpezar;
    private javax.swing.JLabel btnPausar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblF1;
    private javax.swing.JLabel lblF2;
    private javax.swing.JLabel lblF3;
    private javax.swing.JLabel lblF4;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMaquina;
    public javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblV1;
    private javax.swing.JLabel lblV2;
    private javax.swing.JLabel lblV3;
    private javax.swing.JLabel lblV4;
    // End of variables declaration//GEN-END:variables

}
